#!/usr/bin/env python3
"""WP-F0: causal-set admissibility test on existing event DAGs.

Reads the dependency-edge CSVs written by the v16 gates (same DAG definition as
``relational_universe_v16b_intrinsic_event_dag_gate.DependencyDAG``: an edge
parent->child is a RAW/WAW/WAR conflict, event ids are a topological order) and
computes, per history and per scheduler arm:

  G0.1  r / r_floor           r_floor = sum_v depth(v) / C(N,2), depth = longest path in
  G0.2  raw edges/event and links/event after transitive reduction
  G0.3  max |I(p,q)| / N      largest Alexandrov interval over comparable pairs
  G0.4  Theta = r (N-1)/(h-1) h = longest chain (elements)
  Gate1 decimation exponent   s = d ln L / d ln p, L>=8, bootstrap CI

Reference posets (chain bundle, Minkowski sprinklings d=2/4) are generated by
the same code path so the thresholds are compared like against like.

Thresholds are pre-registered in Documentation/Program/WP-F0_dimension_admissibility.md
and are NOT evaluated here beyond a pass/fail column; nothing is tuned.

Usage:
  PYTHONPATH=.codex_pydeps python3 Tools/causet_admissibility.py \
      --edges Documentation/v16b_dependency_edges.csv \
      --edges Documentation/v16c_fine_dependency_edges.csv \
      --edges Documentation/v16d_fine_dependency_edges.csv \
      --out Documentation/Program --draws 20 --references
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import random
import sys
import time
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

DECIMATION_P = (1.0, 0.5, 0.25, 0.125, 0.0625, 0.03125)
THRESH = {"g01_r_over_floor": 2.0, "g02_links_per_event": 5.0, "g03_max_interval_frac": 0.05, "g04_theta": 5.0}


# ----------------------------------------------------------------------------
# Poset core: elements 0..N-1 in topological order, preds[i] = set of direct preds
# ----------------------------------------------------------------------------
class Poset:
    def __init__(self, n: int, preds: Sequence[Sequence[int]]):
        self.n = n
        self.preds = [sorted(set(p)) for p in preds]
        self.anc: List[int] = []
        self.depth: List[int] = []
        for v in range(n):
            bits = 0
            d = 0
            for p in self.preds[v]:
                assert p < v, "edge list is not in topological order"
                bits |= self.anc[p] | (1 << p)
                d = max(d, self.depth[p] + 1)
            self.anc.append(bits)
            self.depth.append(d)
        self.desc = [0] * n
        for v in range(n):
            a = self.anc[v]
            while a:
                low = a & -a
                self.desc[low.bit_length() - 1] |= 1 << v
                a ^= low
        self.edge_count = sum(len(p) for p in self.preds)
        self.comparable = sum(a.bit_count() for a in self.anc)
        self.pairs = n * (n - 1) // 2

    @classmethod
    def from_closure(cls, n: int, anc: List[int]) -> "Poset":
        """Build from a full ancestor relation (used for sprinklings); preds = links."""
        # covers(v) = anc[v] minus everything that is an ancestor of some ancestor of v
        red = []
        for v in range(n):
            a = anc[v]
            shadow = 0
            aa = a
            while aa:
                low = aa & -aa
                shadow |= anc[low.bit_length() - 1]
                aa ^= low
            c = a & ~shadow
            covers = []
            while c:
                low = c & -c
                covers.append(low.bit_length() - 1)
                c ^= low
            red.append(covers)
        return cls(n, red)

    # -- observables -------------------------------------------------------
    def r(self) -> float:
        return self.comparable / self.pairs if self.pairs else 0.0

    def r_floor(self) -> float:
        return sum(self.depth) / self.pairs if self.pairs else 0.0

    def longest_chain(self) -> int:
        return max(self.depth) + 1 if self.n else 0

    def link_count(self) -> int:
        links = 0
        for v in range(self.n):
            ps = self.preds[v]
            for p in ps:
                # p is a cover iff no other direct pred q of v has p as ancestor
                if not any(self.anc[q] >> p & 1 for q in ps if q != p):
                    links += 1
        return links

    def max_interval(self) -> int:
        best = 0
        for q in range(self.n):
            a = self.anc[q]
            while a:
                low = a & -a
                p = low.bit_length() - 1
                a ^= low
                size = (self.desc[p] & self.anc[q]).bit_count() + 2
                if size > best:
                    best = size
        return best

    def decimate(self, p: float, rng: random.Random) -> Tuple[int, int, float]:
        """Return (|S|, L(S), r(S)) for an independent p-thinning, induced from closure."""
        if p >= 1.0:
            return self.n, self.longest_chain(), self.r()
        keep = [v for v in range(self.n) if rng.random() < p]
        mask = 0
        for v in keep:
            mask |= 1 << v
        dep: Dict[int, int] = {}
        comparable = 0
        best = 0
        for v in keep:
            a = self.anc[v] & mask
            comparable += a.bit_count()
            d = 1
            while a:
                low = a & -a
                u = low.bit_length() - 1
                a ^= low
                du = dep[u] + 1
                if du > d:
                    d = du
            dep[v] = d
            if d > best:
                best = d
        m = len(keep)
        pairs = m * (m - 1) // 2
        return m, best, (comparable / pairs if pairs else float("nan"))


# ----------------------------------------------------------------------------
# Myrheim-Meyer with the corrected normalisation r = G(d+1)G(d/2) / (2 G(3d/2))
# ----------------------------------------------------------------------------
def mm_r(d: float) -> float:
    return math.gamma(d + 1) * math.gamma(d / 2) / (2.0 * math.gamma(1.5 * d))


def mm_dimension(r: float) -> float:
    lo, hi = 1.0001, 40.0
    if r >= mm_r(lo):
        return lo
    if r <= mm_r(hi):
        return float("inf")
    for _ in range(200):
        mid = 0.5 * (lo + hi)
        if mm_r(mid) > r:
            lo = mid
        else:
            hi = mid
    return 0.5 * (lo + hi)


# ----------------------------------------------------------------------------
# Decimation fit
# ----------------------------------------------------------------------------
def fit_slope(points: Sequence[Tuple[float, float]]) -> float:
    """OLS slope of ln L on ln p over (p, L) points with L >= 8."""
    xs = [math.log(p) for p, L in points if L >= 8]
    ys = [math.log(L) for p, L in points if L >= 8]
    if len(set(xs)) < 2:
        return float("nan")
    mx = sum(xs) / len(xs)
    my = sum(ys) / len(ys)
    sxx = sum((x - mx) ** 2 for x in xs)
    sxy = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    return sxy / sxx if sxx else float("nan")


def bootstrap_slope(draws: Dict[float, List[int]], rng: random.Random, reps: int = 1000) -> Tuple[float, float, float]:
    pts = [(p, L) for p, Ls in draws.items() for L in Ls]
    s = fit_slope(pts)
    boots = []
    for _ in range(reps):
        sample = []
        for p, Ls in draws.items():
            sample.extend((p, rng.choice(Ls)) for _ in Ls)
        boots.append(fit_slope(sample))
    boots = sorted(b for b in boots if not math.isnan(b))
    if not boots:
        return s, float("nan"), float("nan")
    return s, boots[int(0.025 * len(boots))], boots[min(len(boots) - 1, int(0.975 * len(boots)))]


# ----------------------------------------------------------------------------
# Reference posets
# ----------------------------------------------------------------------------
def chain_bundle(n: int, chains: int) -> Poset:
    preds = [[] for _ in range(n)]
    for v in range(n):
        if v >= chains:
            preds[v] = [v - chains]
    return Poset(n, preds)


def sprinkling(n: int, d: int, rng: random.Random) -> Poset:
    """Uniform sprinkling into a causal diamond of d-dim Minkowski space."""
    pts = []
    if d == 2:
        for _ in range(n):
            pts.append((rng.random(), rng.random()))  # light-cone coords (u,v); diamond = unit square
        pts.sort(key=lambda t: t[0] + t[1])
        anc = []
        for i, (u, v) in enumerate(pts):
            bits = 0
            for j in range(i):
                uj, vj = pts[j]
                if uj < u and vj < v:
                    bits |= 1 << j
            anc.append(bits)
        return Poset.from_closure(n, anc)
    # general d: t in [0,1], |x| <= min(t, 1-t)
    while len(pts) < n:
        t = rng.random()
        x = [rng.uniform(-0.5, 0.5) for _ in range(d - 1)]
        if math.sqrt(sum(c * c for c in x)) <= min(t, 1.0 - t):
            pts.append((t, x))
    pts.sort(key=lambda t: t[0])
    anc = []
    for i, (t, x) in enumerate(pts):
        bits = 0
        for j in range(i):
            tj, xj = pts[j]
            dt = t - tj
            if dt * dt > sum((a - b) ** 2 for a, b in zip(x, xj)):
                bits |= 1 << j
        anc.append(bits)
    return Poset.from_closure(n, anc)


# ----------------------------------------------------------------------------
# Loading histories
# ----------------------------------------------------------------------------
def load_histories(paths: Sequence[Path]) -> List[Tuple[str, str, str, str, Poset]]:
    out = []
    for path in paths:
        groups: Dict[Tuple[str, str, str], List[Tuple[int, int]]] = defaultdict(list)
        with path.open() as fh:
            for row in csv.DictReader(fh):
                key = (row["growth_seed"], row["run_offset"], row["arm"])
                groups[key].append((int(row["parent_event_id"]), int(row["child_event_id"])))
        for (gs, ro, arm), edges in sorted(groups.items()):
            n = max(max(p, c) for p, c in edges) + 1
            preds = [[] for _ in range(n)]
            for p, c in edges:
                preds[c].append(p)
            out.append((path.stem, gs, ro, arm, Poset(n, preds)))
    return out


# ----------------------------------------------------------------------------
def measure(label: str, source: str, gs: str, ro: str, arm: str, poset: Poset, draws: int, rng: random.Random, heartbeat) -> Tuple[dict, List[dict]]:
    t0 = time.time()
    n = poset.n
    r = poset.r()
    rf = poset.r_floor()
    h = poset.longest_chain()
    links = poset.link_count()
    maxI = poset.max_interval()
    theta = r * (n - 1) / (h - 1) if h > 1 else float("nan")
    dec: Dict[float, List[int]] = {}
    dec_r: Dict[float, List[float]] = {}
    dec_rows = []
    for p in DECIMATION_P:
        for k in range(draws if p < 1.0 else 1):
            m, L, rp = poset.decimate(p, rng)
            dec.setdefault(p, []).append(L)
            dec_r.setdefault(p, []).append(rp)
            dec_rows.append({"label": label, "source": source, "growth_seed": gs, "run_offset": ro, "arm": arm, "N": n, "p": p, "draw": k, "kept": m, "L": L, "r_p": rp})
    s, lo, hi = bootstrap_slope(dec, rng)
    row = {
        "label": label, "source": source, "growth_seed": gs, "run_offset": ro, "arm": arm, "N": n,
        "raw_edges": poset.edge_count, "raw_edges_per_event": poset.edge_count / n,
        "links": links, "links_per_event": links / n,
        "comparable_pairs": poset.comparable, "r": r, "r_floor": rf, "r_over_floor": r / rf if rf else float("nan"),
        "longest_chain_h": h, "theta": theta, "max_interval": maxI, "max_interval_frac": maxI / n,
        "d_MM_corrected": mm_dimension(r),
        "decimation_s": s, "s_ci_lo": lo, "s_ci_hi": hi, "s_ci_width": hi - lo,
        "g01_pass": int(r / rf >= THRESH["g01_r_over_floor"]) if rf else 0,
        "g02_pass": int(links / n >= THRESH["g02_links_per_event"]),
        "g03_pass": int(maxI / n >= THRESH["g03_max_interval_frac"]),
        "g04_pass": int(theta >= THRESH["g04_theta"]),
        "seconds": round(time.time() - t0, 1),
    }
    row["gate0_pass"] = int(row["g01_pass"] and row["g02_pass"] and row["g03_pass"] and row["g04_pass"])
    heartbeat(f"{label} {source} {gs}/{ro}/{arm} N={n} r/floor={row['r_over_floor']:.3f} links/ev={links/n:.3f} maxI={maxI/n:.4f} theta={theta:.3f} s={s:.3f} ({row['seconds']}s)")
    return row, dec_rows


def write_csv(path: Path, rows: List[dict]) -> None:
    if not rows:
        return
    with path.open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--edges", action="append", type=Path, default=[])
    ap.add_argument("--out", type=Path, default=Path("Documentation/Program"))
    ap.add_argument("--draws", type=int, default=20)
    ap.add_argument("--references", action="store_true")
    ap.add_argument("--ref-n", type=int, default=2048)
    ap.add_argument("--seed", type=int, default=20260903)
    ap.add_argument("--heartbeat", type=Path, default=Path(".program_logs/WP-F0.heartbeat"))
    args = ap.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    args.heartbeat.parent.mkdir(parents=True, exist_ok=True)

    def heartbeat(msg: str) -> None:
        line = f"{time.strftime('%Y-%m-%dT%H:%M:%S%z')} {msg}"
        print(line, flush=True)
        with args.heartbeat.open("a") as fh:
            fh.write(line + "\n")

    rng = random.Random(args.seed)
    heartbeat(f"start mm_r(2)={mm_r(2):.6f} (must be 0.5)")
    assert abs(mm_r(2) - 0.5) < 1e-12

    rows: List[dict] = []
    dec_rows: List[dict] = []
    if args.references:
        heartbeat("references: chain bundle")
        row, d = measure("ref_chain_bundle_32", "synthetic", "-", "-", "-", chain_bundle(args.ref_n, 32), args.draws, rng, heartbeat)
        rows.append(row); dec_rows.extend(d)
        for dim in (2, 4):
            heartbeat(f"references: sprinkling d={dim} N={args.ref_n}")
            row, d = measure(f"ref_sprinkling_d{dim}", "synthetic", "-", "-", "-", sprinkling(args.ref_n, dim, rng), args.draws, rng, heartbeat)
            rows.append(row); dec_rows.extend(d)

    for source, gs, ro, arm, poset in load_histories(args.edges):
        row, d = measure("history", source, gs, ro, arm, poset, args.draws, rng, heartbeat)
        rows.append(row); dec_rows.extend(d)
        write_csv(args.out / "WP-F0_admissibility_per_history.csv", rows)

    write_csv(args.out / "WP-F0_admissibility_per_history.csv", rows)
    write_csv(args.out / "WP-F0_decimation_draws.csv", dec_rows)

    # per-arm / per-N aggregates with pooled decimation fit
    agg = []
    keys = sorted({(r["label"], r["arm"], r["N"]) for r in rows})
    for label, arm, n in keys:
        sub = [r for r in rows if (r["label"], r["arm"], r["N"]) == (label, arm, n)]
        pooled: Dict[float, List[int]] = defaultdict(list)
        for d in dec_rows:
            if (d["label"], d["arm"], d["N"]) == (label, arm, n):
                pooled[d["p"]].append(d["L"])
        s, lo, hi = bootstrap_slope(pooled, rng)
        def stat(k):
            vals = sorted(r[k] for r in sub)
            return vals[len(vals) // 2], vals[0], vals[-1]
        a = {"label": label, "arm": arm, "N": n, "n_histories": len(sub)}
        for k in ("raw_edges_per_event", "links_per_event", "r", "r_over_floor", "longest_chain_h", "theta", "max_interval_frac", "d_MM_corrected", "decimation_s"):
            med, mn, mx = stat(k)
            a[f"{k}_median"] = med; a[f"{k}_min"] = mn; a[f"{k}_max"] = mx
        a["pooled_s"] = s; a["pooled_s_ci_lo"] = lo; a["pooled_s_ci_hi"] = hi; a["pooled_s_ci_width"] = hi - lo
        a["g01_pass_count"] = sum(r["g01_pass"] for r in sub)
        a["g02_pass_count"] = sum(r["g02_pass"] for r in sub)
        a["g03_pass_count"] = sum(r["g03_pass"] for r in sub)
        a["g04_pass_count"] = sum(r["g04_pass"] for r in sub)
        a["gate0_pass_count"] = sum(r["gate0_pass"] for r in sub)
        agg.append(a)
    write_csv(args.out / "WP-F0_admissibility_by_arm.csv", agg)
    (args.out / "WP-F0_thresholds_frozen.json").write_text(json.dumps({"thresholds": THRESH, "gate1_s_range": [0.20, 0.40], "gate1_ci_width_max": 0.05, "gate1_arm_agreement": 0.05, "decimation_p": DECIMATION_P, "L_min_for_fit": 8}, indent=2))
    heartbeat("done")


if __name__ == "__main__":
    main()
